### ISSUE TITLE
Incorrect handling of eTOXlab error return case

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [BielStela/eTOXlabWS#12]
Model: LQT inc -> fails with error

[Aspiring molfile](https://www.ebi.ac.uk/chembl/download_helper/getmol/1280)
[Prod server](http://84.89.134.152)

  DeprecationWarning)
Parsing Table
0       ERROR:results mismatch  0       0       0       0
0
ERROR:results mismatch
0
0
0
0
[error] play - Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: "None"
[error] application - 

! @749o8d5c1 - Internal server error, for (POST) [/calculate_table] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "None"]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.6.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
Caused by: java.lang.NumberFormatException: For input string: "None"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_131]
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[na:1.8.0_131]
        at java.lang.Float.parseFloat(Float.java:451) ~[na:1.8.0_131]
        at scala.collection.immutable.StringLike$class.toFloat(StringLike.scala:231) ~[org.scala-lang.scala-library-2.10.6.jar:na]
        at scala.collection.immutable.StringOps.toFloat(StringOps.scala:31) ~[org.scala-lang.scala-library-2.10.6.jar:na]
        at controllers.eTOXlab$$anonfun$8.apply(eTOXlab.scala:168) ~[envoy_ws.envoy_ws-1.0.jar:1.0]

**Comment by OriolLopezMassaguer** [comment]
Tested on production server http://84.89.134.152

**Comment by BielStela** [comment]
go to #13
