### ISSUE TITLE
Empty result in certain cases

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [BielStela/eTOXlabWS#13]
Models CAV12 and KCNQ1
return empty table results

Using aspirin molfile:

[Aspirin molfile](https://www.ebi.ac.uk/chembl/download_helper/getmol/1280)

[Prod server](http://84.89.134.152)

**Comment by BielStela** [comment]
![aspirin error](https://user-images.githubusercontent.com/9404338/27026967-ebc62bb2-4f5f-11e7-9ce9-7a2dc7bf76ac.png)
Same Aspirin mol crashes with LQTinc and LQTpot

**Comment by BielStela** [comment]
```
Parsing Table
0	ERROR:results mismatch	0	0	0	0
0
ERROR:results mismatch
0
0
0
0
[error] play - Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: "None"
[error] application - 

! @74al750nn - Internal server error, for (POST) [/calculate_table] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "None"]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10.jar:2.2.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.10.6.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [play_2.10.jar:2.2.6]
Caused by: java.lang.NumberFormatException: For input string: "None"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_131]
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[na:1.8.0_131]
	at java.lang.Float.parseFloat(Float.java:451) ~[na:1.8.0_131]
	at scala.collection.immutable.StringLike$class.toFloat(StringLike.scala:231) ~[scala-library-2.10.6.jar:na]
	at scala.collection.immutable.StringOps.toFloat(StringOps.scala:31) ~[scala-library-2.10.6.jar:na]
	at controllers.eTOXlab$$anonfun$8.apply(eTOXlab.scala:168) ~[classes/:na]
```

**Comment by BielStela** [comment]
problem solved adding $$$$ at the end of the file
